sudo: required
dist: trusty
language: generic
env:
  matrix:
    - LUAJIT=OFF CXX=g++
    - LUAJIT=ON  CXX=g++
    - LUAJIT=OFF CXX=clang++
    - LUAJIT=ON  CXX=clang++
services:
  - docker
before_script:
  - export MYSQL_PASS="$(openssl rand -base64 32)"
  - docker-compose up -d
script:
  - docker-compose run compile cmake /source '&&' make -j2
  - docker-compose run server ./tfs --dry-run
after_script: docker-compose down
