sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
env:
  global:
    - CCACHE_SLOPPINESS=pch_defines,time_macros
    - USE_CCACHE=1
  matrix:
    - LUAJIT=OFF
    - LUAJIT=ON
cache: ccache
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-system-dev
      - libboost-iostreams-dev
      - liblua5.2-dev
      - libluajit-5.1-dev
      - libmysqlclient-dev
      - libpugixml-dev
before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_LUAJIT=${LUAJIT} ..
script: make -j2
